import { CLIError } from "./CLIError.js";


class Command {
    constructor(name, description, action) {
        this.name = name
        this.description = description
        this.action = action
    }
    do(args) {
        return this.action(args)
    }
}

class Commands {
    static print(args) {
        return args.join(" ").replace(",", / /g);
    }
    static error(args) {
        return new CLIError("Error auto generated by error command", 0)
    }
}

// Esto nunca se uso.

class AdvancedCommands extends Commands {
    static print(args) {
        return args
    }
}

export { Commands, Command, AdvancedCommands }


